### get admin
GET http://localhost:3000/admin
### get admin com id
GET http://localhost:3000/admin/250
### get admin via Post
POST http://localhost:3000/admin
Content-Type: application/json

{
    "login" : "rodriguin",
    "senha" : "vrau"
}
### PATCH
PATCH http://localhost:3000/admin/250

### PUT
PUT http://localhost:3000/admin/250

### DELETE
DELETE http://localhost:3000/admin/250